import { NextRequest, NextResponse } from "next/server";
import { GeneratedPack } from "@/types";
import { formatDate } from "@/lib/utils";

function buildBinderHtml(pack: GeneratedPack): string {
  const docTypeLabels: Record<string, string> = {
    sop: "Standard Operating Procedure",
    checklist: "Checklist",
    form: "Form",
    policy: "Policy",
    log: "Log Sheet",
    cover: "Cover Page",
  };

  const coverPage = `
    <div class="page cover-page">
      <div class="cover-header">
        <div class="cover-logo">📋</div>
        <h1 class="cover-title">${pack.businessName}</h1>
        <h2 class="cover-subtitle">Compliance Documentation Binder</h2>
        <div class="cover-niche">${pack.niche.charAt(0).toUpperCase() + pack.niche.slice(1)} Operations</div>
      </div>
      <div class="cover-meta">
        <table>
          <tr><td><strong>Version:</strong></td><td>${pack.version}</td></tr>
          <tr><td><strong>Prepared On:</strong></td><td>${formatDate(pack.generatedAt)}</td></tr>
          <tr><td><strong>Status:</strong></td><td>${pack.status === "draft" ? "⚠️ Draft – Needs Review" : "✅ Ready"}</td></tr>
          <tr><td><strong>Generated By:</strong></td><td>Auditt Documentation System</td></tr>
        </table>
      </div>
      <div class="disclaimer">
        <strong>Important Notice:</strong> This binder was generated by AI to assist with documentation.
        It is not legal advice. Always review and adapt to your local regulations before use.
        Items marked [NEEDS REVIEW] require manual verification.
      </div>
    </div>
  `;

  const indexEntries = pack.sections
    .map(
      (s, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${s.title}</td>
        <td>${docTypeLabels[s.type] || s.type}</td>
        <td>${s.isDraft ? "⚠️ Draft" : "✅ Ready"}</td>
      </tr>`
    )
    .join("");

  const indexPage = `
    <div class="page">
      <div class="page-header">
        <span>${pack.businessName}</span>
        <span>Compliance Binder ${pack.version}</span>
      </div>
      <h2>Table of Contents</h2>
      <table class="index-table">
        <thead>
          <tr><th>#</th><th>Document Title</th><th>Type</th><th>Status</th></tr>
        </thead>
        <tbody>${indexEntries}</tbody>
      </table>
      <div class="revision-history">
        <h3>Revision History</h3>
        <table>
          <thead><tr><th>Version</th><th>Date</th><th>Description</th><th>Prepared By</th></tr></thead>
          <tbody>
            <tr>
              <td>${pack.version}</td>
              <td>${formatDate(pack.generatedAt)}</td>
              <td>Initial generation via Auditt</td>
              <td>Auditt System</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `;

  const sectionPages = pack.sections
    .map(
      (s, i) => `
    <div class="page document-page">
      <div class="page-header">
        <span>${pack.businessName}</span>
        <span>${pack.version} | Doc ${i + 1} of ${pack.sections.length}</span>
      </div>
      ${s.isDraft ? '<div class="draft-banner">⚠️ DRAFT – Needs Review before use</div>' : ""}
      <div class="doc-content">
        ${s.content}
      </div>
      <div class="page-footer">
        <span>${s.title}</span>
        <span>Prepared: ${formatDate(pack.generatedAt)}</span>
        <span>Page ${i + 2}</span>
      </div>
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${pack.businessName} - Compliance Binder ${pack.version}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #1a1a2e; background: #fff; }
    .page { width: 210mm; min-height: 297mm; padding: 20mm 18mm; page-break-after: always; position: relative; }
    .cover-page { background: linear-gradient(135deg, #0f3460 0%, #16213e 100%); color: #fff; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; }
    .cover-logo { font-size: 60pt; margin-bottom: 20px; }
    .cover-title { font-size: 28pt; font-weight: 700; margin-bottom: 10px; }
    .cover-subtitle { font-size: 16pt; font-weight: 400; opacity: 0.85; margin-bottom: 16px; }
    .cover-niche { background: rgba(255,255,255,0.2); padding: 6px 20px; border-radius: 20px; font-size: 12pt; margin-bottom: 30px; }
    .cover-meta { background: rgba(255,255,255,0.1); border-radius: 8px; padding: 20px 30px; margin-bottom: 30px; min-width: 320px; }
    .cover-meta table { width: 100%; border-collapse: collapse; }
    .cover-meta td { padding: 6px 12px; color: #fff; font-size: 11pt; }
    .cover-meta td:first-child { font-weight: 600; text-align: right; padding-right: 16px; opacity: 0.8; width: 130px; }
    .disclaimer { background: rgba(255,255,255,0.15); border-left: 4px solid #e94560; padding: 12px 16px; font-size: 9pt; line-height: 1.5; text-align: left; max-width: 480px; border-radius: 4px; }
    .page-header { display: flex; justify-content: space-between; font-size: 8pt; color: #666; border-bottom: 1px solid #dee2e6; padding-bottom: 6px; margin-bottom: 20px; }
    .page-footer { display: flex; justify-content: space-between; font-size: 8pt; color: #666; border-top: 1px solid #dee2e6; padding-top: 6px; margin-top: 20px; position: absolute; bottom: 15mm; left: 18mm; right: 18mm; }
    .draft-banner { background: #fff3cd; border: 1px solid #ffc107; color: #856404; padding: 8px 14px; border-radius: 4px; margin-bottom: 16px; font-size: 9pt; font-weight: 600; }
    h2 { font-size: 18pt; color: #0f3460; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #0f3460; }
    h3 { font-size: 13pt; color: #16213e; margin: 16px 0 8px; }
    p { margin-bottom: 10px; line-height: 1.6; }
    ul, ol { margin: 8px 0 12px 20px; }
    li { margin-bottom: 4px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10pt; }
    th { background: #0f3460; color: #fff; padding: 8px 10px; text-align: left; font-size: 9pt; }
    td { padding: 7px 10px; border: 1px solid #dee2e6; }
    tr:nth-child(even) td { background: #f8f9fa; }
    .index-table th { background: #0f3460; }
    .revision-history { margin-top: 30px; }
    .doc-content h2 { font-size: 16pt; }
    .doc-content h3 { font-size: 12pt; }
    @media print {
      .page { page-break-after: always; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  ${coverPage}
  ${indexPage}
  ${sectionPages}
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  let pack: GeneratedPack;
  try {
    pack = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  if (!pack || !pack.sessionId || !pack.sections) {
    return NextResponse.json(
      { error: "Invalid pack data" },
      { status: 400 }
    );
  }

  const html = buildBinderHtml(pack);

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="${pack.businessName.replace(/[^a-z0-9]/gi, "_")}_Binder_${pack.version}.html`,
      "Cache-Control": "no-store",
    },
  });
}
